services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    expose:
      - 5173
    working_dir: /app-frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    working_dir: /backend-app
    volumes:
      - ./backend:/backend-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      timeout: 10s
      retries: 5
    expose:
      - 3001